### ISSUE TITLE
「or use the older convention of prefixing such globals with an underscore」は「古い規約」ではないのでは?

### ISSUE THREAD

**Issue by hhsprings** [mumumu/pep8-ja#4]
Global Variable Names のアンダースコアルールなのですが、これ、「昔はそうだったが今は違う」、というニュアンスが
出てるとマズくないですか? 古い仕組みだから根絶せよ、なんて誰も思ってないですよね。

原文の意味はこれは、「`__all__` 方式が後から追加されたシカケ」、「アンダースコアルールは、`__all__` 方式が
出来る前から機能している昔からの慣習」という意味での「older」。(そもそも `__all__` の方が新しいので良い仕組みである、
ということも別に言ってないと思うのです。)

訳語としては単に「より古くからの慣習である～」でいいと思います。

**Comment by mumumu** [comment]
コメントありがとうございます。

> 「昔はそうだったが今は違う」、というニュアンスが出てるとマズくないですか? 古い仕組みだから根絶せよ、なんて誰も思ってないですよね。

`古い規約` と訳すとそう読めてしまう、ということですよね

Global Variable Names のアンダースコアルールは、PEP8 が初めてコミットされた　2001年の時点でも存在していたものです。 そして、今もアンダースコアを使うルールは Global Variable Name 以外でも言及されているので、 **今も生きている規約であり、過去のものではない** と理解しています。

> 訳語としては単に「より古くからの慣習である～」でいいと思います。

そうですね。「規約」なのか「慣習」なのかはともかく、以下のように修正しようと思いますが、どうでしょうか？

```diff
- エクスポートしたくないグローバル変数の頭にアンダースコアをつける古い規約を使うべきです
+ エクスポートしたくないグローバル変数の頭にアンダースコアをつける以前からある規約を使うべきです
```

**Comment by hhsprings** [comment]
修正案の通りで良いと思います。(「慣習」のほうがしっくりくるなぁというのはありますが、まぁこれはどちらでも。)

**Comment by mumumu** [comment]
> 修正案の通りで良いと思います。

修正案の通り対応したものをコミットしました。ありがとうございました。

> 「慣習」のほうがしっくりくるなぁというのはありますが、まぁこれはどちらでも。

ここは悩みどころではあります。

基本的に PEP 8 に書かれているのは「言語仕様として強制はしないけどマナー的に守ってね」というルールの集まりなので、「慣習」でも「規約」でも、どちらでも言おうと思えば通りそうに見えてしまうからです。

まあ、いったんは「規約」のままで :pray:
